# -*- coding: utf-8 -*-
"""week 9(3).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ey6VvqOIZAiR2sCcd_uXdFwkh9eeYUtC

Q-1 Name any five plots that we can plot the seaborn library . Also state the uses of each plot.

Ans-1
1. SCATTER PLOT : scatter plot are used to visualize the relationship between two continuous variable .Each data points is represented as a point on the graph.

2. LINE PLOT : Line plot are suitable for visualizing data over a continuous interval or time span .They are often used to display trends or patterns in data.

3. BAR PLOT : Bar plots are used to display the distribution of a categorical variable or to compare the values of different categories . They are especially usefull for visualizing counts of frequency.

4. HISTOGRAM : Histogram are used to represent the distribution of single continuous variable .They divide the data into bins and display the frequency of data points within each bin.

5. BOX PLOT : Box plot are used to display the distribution and spread of a dataset .They show the median .upper and lower quartiles, as well as outliers .They are useful  for detecting skewness and outliers.
"""



"""Q-2 Load the "fmri" dataset using the load_dataset function of seaborn .Plot a line using x="timepoint" and y="signal" for different events and regions."""

import seaborn as sns

fmri=sns.load_dataset("fmri")

fmri

sns.lineplot(x=fmri.timepoint,y=fmri.signal)

sns.lineplot(x=fmri.event	,y=fmri.region	)



"""Q-3 Load the "titanic" dataset using the load_dataset function of seaborn . Plot two box plots using x='pclass' ,y='age' and y='fare'."""

titanic=sns.load_dataset("titanic")

titanic

sns.boxplot(x=titanic.pclass,y=titanic.age)

sns.boxplot(x=titanic.pclass,y=titanic.fare)



"""Q-4 Use the "diamonds" dataset from seaborn to plot a histogram for the 'price' columns .Use the hue parameters for the columns of the diamonds dataset."""

diamonds=sns.load_dataset("diamonds")

diamonds

sns.histplot(diamonds['price'])

sns.histplot(diamonds['cut'])

sns.scatterplot(x=diamonds.x ,y=diamonds.y ,hue=diamonds.cut)

"""Q-5 Use the "iris" dataset from seaborn to plot a pair plot. Use the hue parameters for the "species" column of the iris dataset."""

iris=sns.load_dataset("iris")

iris

sns.pairplot(iris)

sns.boxenplot(x=iris.sepal_length	,y=iris.sepal_width , hue=iris.species)



"""Q-6 Use the "flights" dataset from seaborn to plot a heatmap."""

flights=sns.load_dataset("flights")

flights

